# Generated by Django 6.0.5 on 2026-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color_variants',
            field=models.ManyToManyField(blank=True, help_text='Select all available colors for this product', related_name='products', to='Website.colorvariant'),
        ),
    ]
