# Generated by Django 6.0.5 on 2026-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_remove_product_color_product_color_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at', 'order'],
            },
        ),
    ]
