# Generated by Django 6.0.5 on 2026-05-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoofType',
            new_name='ProductType',
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='roof_type',
            new_name='product_type',
        ),
    ]
