# Generated by Django 6.0.5 on 2026-05-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_rename_rooftype_producttype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_variants',
            field=models.ManyToManyField(blank=True, related_name='products', to='Website.colorvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
