# Generated by Django 6.0.5 on 2026-05-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_alter_contactmessage_options_product_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-uploaded_at']},
        ),
    ]
