# Generated by Django 6.0.5 on 2026-06-03 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_alter_galleryimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoofGauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('price_multiplier', models.DecimalField(decimal_places=3, default=1.0, max_digits=5)),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Roof Gauge',
                'verbose_name_plural': 'Roof Gauges',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoofingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('cover_width', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('default_sheet_price', models.DecimalField(decimal_places=2, default=1800, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Roofing Profile',
                'verbose_name_plural': 'Roofing Profiles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='colorvariant',
            options={'ordering': ['name'], 'verbose_name': 'Color Variant', 'verbose_name_plural': 'Color Variants'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.CreateModel(
            name='RoofEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('roof_type', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pitch', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('include_screws', models.BooleanField(default=True)),
                ('include_nails', models.BooleanField(default=True)),
                ('include_timber', models.BooleanField(default=True)),
                ('include_rainwater', models.BooleanField(default=True)),
                ('rainfall', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('roof_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recommended_sheets', models.PositiveIntegerField(default=0)),
                ('ridge_caps', models.PositiveIntegerField(default=0)),
                ('screws', models.PositiveIntegerField(default=0)),
                ('nails', models.PositiveIntegerField(default=0)),
                ('timber_length', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rainwater_litres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sheet_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ridge_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('screw_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timber_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('sent', 'Sent'), ('approved', 'Approved')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gauge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Website.roofgauge')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Website.roofingprofile')),
            ],
            options={
                'verbose_name': 'Roof Estimate',
                'verbose_name_plural': 'Roof Estimates',
                'ordering': ['-created_at'],
            },
        ),
    ]
