# Generated by Django 6.0.5 on 2026-06-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_roofgauge_roofingprofile_alter_colorvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roofestimate',
            name='eaves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='end_lap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='end_overhang',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='sheet_total_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='sheet_total_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='side_lap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
