# Generated by Django 6.0.5 on 2026-06-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_roofestimate_eaves_roofestimate_end_lap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roofestimate',
            name='calculation_method',
            field=models.CharField(choices=[('dimensions', 'Dimensions (Length × Width)'), ('direct_area', 'Direct Area (m²)')], default='dimensions', max_length=20),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='direct_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Used when calculation_method is 'direct_area'", max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductGaugeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finish_type', models.CharField(blank=True, help_text='e.g., Matt Finish, Glossy, etc.', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.roofgauge')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gauge_variants', to='Website.product')),
            ],
            options={
                'verbose_name': 'Product Gauge Variant',
                'verbose_name_plural': 'Product Gauge Variants',
                'ordering': ['order', 'gauge__order'],
                'unique_together': {('product', 'gauge', 'finish_type')},
            },
        ),
    ]
