# Generated by Django 6.0.5 on 2026-06-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roofestimate',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='project_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='roofestimate',
            name='project_location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='roofestimate',
            name='status',
            field=models.CharField(choices=[('requested', 'Pending Review'), ('in_progress', 'In Progress'), ('quote_ready', 'Quote Ready'), ('approved', 'Approved'), ('expired', 'Expired')], default='requested', max_length=20),
        ),
    ]
