# Generated by Django 6.0.5 on 2026-06-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_roofestimate_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='supabase_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
