# Generated by Django 6.0.5 on 2026-06-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_galleryimage_supabase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='supabase_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
